### ISSUE TITLE
Throws Error As mentioned Below

### ISSUE THREAD

**Issue by AkshayMalani** [rahulmkadam92/Ecommerce#1]
Hi ,
I tried to replicate your application by using the same DB data using get requests and luckily i got all your data dump using get request. When i try to replicate the same DB instance in my local, I'm getting the below error 

"[2:37:04 AM] [Algolia-sync]  ->  Error  ->  { CastError: Cast to ObjectId failed for value "true" at path "_id" for model "User"

I assume this is a type mismatch error , but i do want to understand why this error when the same data is used in both our applications .
Please reply at the earliest.

Attached is the data files which i have extracted using get request from the DB to know the schema.

[data_files.zip](https://github.com/rahulmkadam92/Ecommerce/files/2658800/data_files.zip)

**Comment by gneatfosacho** [comment]
This seems to be "Algolia" error, For Search Feature in the application [Algolia](https://www.algolia.com/) platform was used.

When using Algolia a new unique pass key was generated(different for every Algolia user) and used in this Application. It is similar to using AWS S3 generation of pass key.

The account through which such pass key was generated has been shutdown, which could be the reason for its failure.

**Comment by AkshayMalani** [comment]
Hi Rahul,
I tried creating new Algolia account and change the api key and appln ID values in the application config files. But still it's not working. I assume there might be some other error associated with this which i'm not able to figure out.
Can you help me getting through this?

**Comment by gneatfosacho** [comment]
Check this course:

https://www.udemy.com/build-amazon-clone-angular5-node/
